---
name: Pre-Release

on:
  push:
    branches:
      - main
    tags-ignore:
      - 'v*'

jobs:
  pre-release:
    name: Pre Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: GuillaumeFalourd/setup-rsync@v1

      - name: Install npm dependencies
        run: npm install

      - name: ZIP the plugin
        run: npm run plugin-zip

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest
          prerelease: true
          title: Development Build
          files: ./quiz-blocks.zip